### ISSUE TITLE
Workload not working with latest CPython 3.7-a2

### ISSUE THREAD

**Issue by wardhan7-zz** [Instagram/django-workload#32]
The django-workload is incompatible with CPython 3.7-a2 because of the dependency of cassandra-driver on Cython. In CPython 3.7-a2, they have changed await to keyword which is used in Cython as a variable. This issue has been fixed in Cython 0.27.2.

 cythoning /tmp/pip-build-k3vwmyyc/Cython/Cython/Plex/Scanners.py to /tmp/pip-build-k3vwmyyc/Cython/Cython/Plex/Scanners.c
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-k3vwmyyc/Cython/setup.py", line 326, in <module>
        **setup_args
      File "/home/lp-jenkins/persistent_data/python/master/tmp/build/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/lp-jenkins/persistent_data/python/master/tmp/build/lib/python3.7/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/lp-jenkins/persistent_data/python/master/tmp/build/lib/python3.7/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/lp-jenkins/django-venv/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/lp-jenkins/persistent_data/python/master/tmp/build/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/lp-jenkins/persistent_data/python/master/tmp/build/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/lp-jenkins/persistent_data/python/master/tmp/build/lib/python3.7/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/lp-jenkins/persistent_data/python/master/tmp/build/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/lp-jenkins/persistent_data/python/master/tmp/build/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/lp-jenkins/persistent_data/python/master/tmp/build/lib/python3.7/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-k3vwmyyc/Cython/Cython/Distutils/build_ext.py", line 164, in run
        _build_ext.build_ext.run(self)
      File "/home/lp-jenkins/persistent_data/python/master/tmp/build/lib/python3.7/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-build-k3vwmyyc/Cython/Cython/Distutils/build_ext.py", line 171, in build_extensions
        ext.sources = self.cython_sources(ext.sources, ext)
      File "/tmp/pip-build-k3vwmyyc/Cython/Cython/Distutils/build_ext.py", line 324, in cython_sources
        full_module_name=module_name)
      File "/tmp/pip-build-k3vwmyyc/Cython/Cython/Compiler/Main.py", line 688, in compile
        return compile_single(source, options, full_module_name)
      File "/tmp/pip-build-k3vwmyyc/Cython/Cython/Compiler/Main.py", line 638, in compile_single
        return run_pipeline(source, options, full_module_name)
      File "/tmp/pip-build-k3vwmyyc/Cython/Cython/Compiler/Main.py", line 455, in run_pipeline
        from . import Pipeline
      File "/tmp/pip-build-k3vwmyyc/Cython/Cython/Compiler/Pipeline.py", line 9, in <module>
        from .Visitor import CythonTransform
      File "/tmp/pip-build-k3vwmyyc/Cython/Cython/Compiler/Visitor.py", line 15, in <module>
        from . import ExprNodes
      File "/tmp/pip-build-k3vwmyyc/Cython/Cython/Compiler/ExprNodes.py", line 2809
        await = None
              ^
    SyntaxError: invalid syntax

**Comment by wardhan7-zz** [comment]
The workload is dependent on Django-Cassandra-Engine whose latest release is 1.2.2. The Django-Cassandra-Engine is itself dependent on cassandra-driver with hard-coded version 3.11.0 as requirement. cassandra-driver version. cassandra-driver has dependency on Cython, cssandra-driver 3.11.0 has cython dependency as >=0.20,!0.25,<.26, which is the main issue. Since all cython version < 0.27.2 won't work with CPython 3.7.0-a2. This issue has been fixed in cassandra-driver version 3.12.0. But there is no release available of Django-Cassandra-Engine which bumps up the requirement of cassandra-driver to 3.12.0 from 3.11.0. 
I have posted this thing on Django-Cassandra-Engine's Issue portal :
https://github.com/r4fek/django-cassandra-engine/issues/104

**Comment by cooperlees** [comment]
Awesome. Thanks for reporting!
